server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  mapperLocations: classpath:lx/mq/mapper/*Mapper.xml


